spring.application.name=patient-appGobal
spring.datasource.url=jdbc:postgresql://localhost:5432/patients
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=Margrete@1
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate=debug
server.port=8111
#spring.sql.init.mode=always

spring.jpa.show-sql=true
